server:
  port: 18080
  servlet:
    context-path: /target
user:
  username: zheng
  password: 123456
  nickname:
    - 郑
    - 鑫
    - 雨
  mobels:
    - num: 01
      brand: 李宁
    - num: 02
      brand: 阿迪
person:
  name: zhaobingge
  age: 18